//go:build !aspect
// Automatically generated by AspectGo (github.com/AkihiroSuda/aspectgo)
// DO NOT EDIT MANUALLY

package main

import aspectrt "github.com/AkihiroSuda/aspectgo/aspect/rt"

import (
	"fmt"

	"github.com/AkihiroSuda/aspectgo/example/receiver2/pkg1"
	. "github.com/AkihiroSuda/aspectgo/example/receiver2/pkg1"
	xpkg1 "github.com/AkihiroSuda/aspectgo/example/receiver2/pkg1"
	"github.com/AkihiroSuda/aspectgo/example/receiver2/pkg2"
	xpkg2 "github.com/AkihiroSuda/aspectgo/example/receiver2/pkg2"
)

func main() {
	s1 := pkg1.S{}
	fmt.Println((_ag_pgen_ag_proxy_0(&s1))("pkg1.S{}"))
	s1p := &pkg1.S{}
	fmt.Println((_ag_pgen_ag_proxy_1(s1p))("&pkg1.S{}"))

	s2 := pkg2.S{}
	fmt.Println(s2.Foo("pkg2.S{} (should be ignored)"))

	s := S{}
	fmt.Println((_ag_pgen_ag_proxy_2(&s))("S{}"))

	xs1 := xpkg1.S{}
	fmt.Println((_ag_pgen_ag_proxy_3(&xs1))("xpkg1.S{}"))

	xs2 := xpkg2.S{}
	fmt.Println(xs2.Foo("xpkg2.S{} (should be ignored)"))

	fmt.Println((_ag_pgen_ag_proxy_4((&pkg1.S{})))("(&pkg1.S{})"))
	fmt.Println((&pkg2.S{}).Foo("(&pkg2.S{}) (should be ignored)"))
	fmt.Println((_ag_pgen_ag_proxy_5((&S{})))("(&S{})"))
}

func _ag_proxy_0(_ag_recv *pkg1.S, x string) ( string) {
	_ag_res := (&Pkg1SAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(string)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(string)
	return _ag_res0
}

func _ag_pgen_ag_proxy_0(_ag_recv *pkg1.S) func(string) string {
	return func(x string) ( string) {
		return _ag_proxy_0(_ag_recv, x)
	}
}

func _ag_proxy_1(_ag_recv *pkg1.S, x string) ( string) {
	_ag_res := (&Pkg1SAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(string)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(string)
	return _ag_res0
}

func _ag_pgen_ag_proxy_1(_ag_recv *pkg1.S) func(string) string {
	return func(x string) ( string) {
		return _ag_proxy_1(_ag_recv, x)
	}
}

func _ag_proxy_2(_ag_recv *pkg1.S, x string) ( string) {
	_ag_res := (&Pkg1SAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(string)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(string)
	return _ag_res0
}

func _ag_pgen_ag_proxy_2(_ag_recv *pkg1.S) func(string) string {
	return func(x string) ( string) {
		return _ag_proxy_2(_ag_recv, x)
	}
}

func _ag_proxy_3(_ag_recv *pkg1.S, x string) ( string) {
	_ag_res := (&Pkg1SAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(string)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(string)
	return _ag_res0
}

func _ag_pgen_ag_proxy_3(_ag_recv *pkg1.S) func(string) string {
	return func(x string) ( string) {
		return _ag_proxy_3(_ag_recv, x)
	}
}

func _ag_proxy_4(_ag_recv *pkg1.S, x string) ( string) {
	_ag_res := (&Pkg1SAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(string)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(string)
	return _ag_res0
}

func _ag_pgen_ag_proxy_4(_ag_recv *pkg1.S) func(string) string {
	return func(x string) ( string) {
		return _ag_proxy_4(_ag_recv, x)
	}
}

func _ag_proxy_5(_ag_recv *pkg1.S, x string) ( string) {
	_ag_res := (&Pkg1SAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(string)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(string)
	return _ag_res0
}

func _ag_pgen_ag_proxy_5(_ag_recv *pkg1.S) func(string) string {
	return func(x string) ( string) {
		return _ag_proxy_5(_ag_recv, x)
	}
}
