// Package consts provides constant values for AspectGo.
package consts

// AspectGoPackagePath is the path for AspectGo.
const AspectGoPackagePath = "github.com/AkihiroSuda/aspectgo"

// AutogenFileHeader is the header for auto-generated files.
const AutogenFileHeader = `//go:build !aspect
// Automatically generated by AspectGo (` + AspectGoPackagePath + `)
// DO NOT EDIT MANUALLY

`
