// Automatically generated by AspectGo (github.com/AkihiroSuda/aspectgo)
// DO NOT EDIT MANUALLY

package main

import aspectrt "github.com/AkihiroSuda/aspectgo/aspect/rt"

import (
	"fmt"
)

func sayHello(s string) {
	fmt.Println("hello " + s)
}

func main() {
	(_ag_pgen_ag_proxy_0())("world")
}

func _ag_proxy_0(s string) {
	_ag_res := (&ExampleAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{s}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(string)
		sayHello(_ag_arg0)
		_ag_res := []interface {
		}{}
		return _ag_res
	}, XReceiver: nil})
	_ = _ag_res
	return
}

func _ag_pgen_ag_proxy_0() func(string) {
	return func(s string) {
		_ag_proxy_0(s)
	}
}
