//go:build !aspect
// Automatically generated by AspectGo (github.com/AkihiroSuda/aspectgo)
// DO NOT EDIT MANUALLY

package main

import aspectrt "github.com/AkihiroSuda/aspectgo/aspect/rt"

import (
	"fmt"
)

type I interface {
	Foo(x int) int
}

type S struct {
	X int
}

func (s *S) Foo(x int) int {
	fmt.Printf("hello (x=%d, s.X=%d)\n", x, s.X)
	old := s.X
	s.X = x
	return old
}

func makeI() I {
	return &S{}
}

func main() {
	i := makeI()
	(_ag_pgen_ag_proxy_0(i))(420)
	(_ag_pgen_ag_proxy_1(i))(430)

	var f func(int) int
	f = (_ag_pgen_ag_proxy_2(i))
	f(440)
}

func _ag_proxy_0(_ag_recv I, x int) ( int) {
	_ag_res := (&IAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(int)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(int)
	return _ag_res0
}

func _ag_pgen_ag_proxy_0(_ag_recv I) func(int) int {
	return func(x int) ( int) {
		return _ag_proxy_0(_ag_recv, x)
	}
}

func _ag_proxy_1(_ag_recv I, x int) ( int) {
	_ag_res := (&IAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(int)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(int)
	return _ag_res0
}

func _ag_pgen_ag_proxy_1(_ag_recv I) func(int) int {
	return func(x int) ( int) {
		return _ag_proxy_1(_ag_recv, x)
	}
}

func _ag_proxy_2(_ag_recv I, x int) ( int) {
	_ag_res := (&IAspect{}).Advice(&aspectrt.ContextImpl{XArgs: []interface {
	}{x}, XFunc: func(_ag_args []interface {
	}) []interface {
	} {
		_ag_arg0 := _ag_args[0].(int)
		_ag_res0 := _ag_recv.Foo(_ag_arg0)
		_ag_res := []interface {
		}{_ag_res0}
		return _ag_res
	}, XReceiver: _ag_recv})
	_ = _ag_res
	_ag_res0, _ := _ag_res[0].(int)
	return _ag_res0
}

func _ag_pgen_ag_proxy_2(_ag_recv I) func(int) int {
	return func(x int) ( int) {
		return _ag_proxy_2(_ag_recv, x)
	}
}
